# Generated by Django 3.2.3 on 2021-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=70)),
                ('subject', models.TextField(default='', max_length=70)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
